[project]
name = "notion-runpod-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "notion-client>=2.7.0",
    "runpod>=1.8.1",
]
